version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.test
    restart: unless-stopped
    depends_on:
      - db
      - cache
    ports:
      - ${APPLICATION_EXPOSE:-8000}:8000
    expose:
      - ${APPLICATION_EXPOSE:-8000}
    env_file:
      - ./env/.env.test
    environment:
      - ENVIRONMENT=TEST
    command: /app/script/start_test.sh

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-test}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_EXPOSE:-5432}:5432
    expose:
      - ${POSTGRES_EXPOSE:-5432}

  cache:
    image: redis:6.2
    ports:
      - ${REDIS_EXPOSE:-6379}:6379
    expose:
      - ${REDIS_EXPOSE:-6379}
    restart: unless-stopped
    command: >
      --requirepass ${REDIS_PASSWORD:-redis_user}

volumes:
  cache_data: null
  db_data: null
